[package]
name = "aoc2020_day2"
version = "0.1.0"
authors = ["Johan Toft <johan.toft@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day2"
path = "day2.rs"

[dependencies]
regex = "1"