[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Johan Toft <johan.toft@smarteye.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

regex = "1"
logos = "0.11.4"

[[bin]]
name = "day5"
path = "day5.rs"
